---
name: "Build and Push Container"
description: "Build and push a Docker image with Nautobot-style semver tagging"

inputs:
  images:
    description: "Full image name(s) (e.g. ghcr.io/org/repo)"
    required: true
  python-version:
    description: "Python version for the build matrix"
    required: true
  nautobot-version:
    description: "Nautobot version to install (either PEP440 or branch name)"
    required: true
  target:
    description: "Dockerfile target stage"
    required: true
    default: "final"
  push:
    description: "Whether to push the image"
    required: false
    default: "false"
  platforms:
    description: "Target platforms"
    required: false
    default: "linux/amd64,linux/arm64"
  cache-scope:
    description: "GHA cache scope prefix"
    required: false
    default: ""
  default-python-version:
    description: "Default Python version to use for 'latest' tag"
    required: true
  set-latest:
    description: "Whether to set the 'latest' and stable tag for releases"
    required: false
    default: "false"

outputs:
  tags:
    description: "Generated Docker tags"
    value: "${{ steps.dockermeta.outputs.tags }}"
  labels:
    description: "Generated Docker labels"
    value: "${{ steps.dockermeta.outputs.labels }}"
  digest:
    description: "Image digest"
    value: "${{ steps.build.outputs.digest }}"

runs:
  using: "composite"
  steps:
    - name: "Clean nautobot-version Input in Case of Leading 'v' and Valid Version Check"
      id: "cleannautobotversion"
      shell: "python"
      run: |
        import sys
        from packaging.version import Version, InvalidVersion
        nautobot_version = "${{ inputs.nautobot-version }}"
        if nautobot_version.startswith("v"):
            candidate_version = nautobot_version[1:]
        else:
            candidate_version = nautobot_version
        try:
            v = Version(candidate_version)
            clean_version = candidate_version
        except InvalidVersion:
            clean_version = nautobot_version  # keep original if not valid version
        print(f"::set-output name=clean-version::{clean_version}")
    - name: "Determine if Nautobot Version is Pre-release"
      id: "prereleasecheck"
      shell: "python"
      run: |
        import sys
        from packaging.version import Version, InvalidVersion

        nautobot_version = "${{ steps.cleannautobotversion.outputs.clean-version }}"

        try:
            v = Version(nautobot_version)
            is_prerelease = v.is_prerelease
        except InvalidVersion:
            is_prerelease = True  # assume branch names are not stable releases

        print(f"::set-output name=is-prerelease::{str(is_prerelease).lower()}")  
    - name: "Docker Metadata"
      id: "dockermeta"
      uses: "docker/metadata-action@v5"
      with:
        images: "${{ inputs.images }}"
        flavor: |
          latest=${{ steps.prereleasecheck.outputs.is-prerelease == 'false' && inputs.python-version == inputs.default-python-version }}
        tags: |
          type=raw,value=${{ steps.cleannautobotversion.outputs.clean-version }}-py${{ inputs.python-version }}
          type=raw,value=${{ steps.cleannautobotversion.outputs.clean-version }},enable=${{ inputs.python-version == inputs.default-python-version }}
          type=pep440,pattern={{major}}.{{minor}}-py${{ inputs.python-version }},value=${{ steps.cleannautobotversion.outputs.clean-version }},match=v(\d.\d.\d),enable=${{ steps.prereleasecheck.outputs.is-prerelease == 'false' }}
          type=pep440,pattern={{major}}.{{minor}},value=${{ steps.cleannautobotversion.outputs.clean-version }},match=v(\d.\d.\d),enable=${{ steps.prereleasecheck.outputs.is-prerelease == 'false' && inputs.python-version == inputs.default-python-version }}
          type=raw,value=latest,enable=${{ steps.prereleasecheck.outputs.is-prerelease == 'false' && inputs.set-latest == 'true' && inputs.python-version == inputs.default-python-version }}
          type=raw,value=latest-py${{ inputs.python-version }},enable=${{ steps.prereleasecheck.outputs.is-prerelease == 'false' && inputs.set-latest == 'true' }}
          type=raw,value=stable,enable=${{ steps.prereleasecheck.outputs.is-prerelease == 'false' && inputs.set-latest == 'true' && inputs.python-version == inputs.default-python-version }}
          type=raw,value=stable-py${{ inputs.python-version }},enable=${{ steps.prereleasecheck.outputs.is-prerelease == 'false' && inputs.set-latest == 'true' }}
        labels: |
          org.opencontainers.image.title=Nautobot

    - name: "Log tags"
      shell: "bash"
      run: |
        echo "=== Tags for ${{ inputs.image }} (py${{ inputs.python-version }}) ==="
        echo "${{ steps.dockermeta.outputs.tags }}"

    - name: "Build and Push"
      id: "build"
      uses: "docker/build-push-action@v6"
      with:
        push: "${{ inputs.push }}"
        target: "${{ inputs.target }}"
        platforms: "${{ inputs.platforms }}"
        tags: "${{ steps.dockermeta.outputs.tags }}"
        labels: "${{ steps.dockermeta.outputs.labels }}"
        cache-from: "type=gha,scope=${{ inputs.cache-scope }}-${{ inputs.python-version }}"
        cache-to: "type=gha,mode=max,scope=${{ inputs.cache-scope }}-${{ inputs.python-version }}"
        context: "."
        build-args: |
          PYTHON_VER=${{ matrix.python-version }}
          POETRY_INSTALLER_PARALLEL=false
